services:

#  discovery-server:
#    image: amigoscode/discovery-server:latest
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin

  movie-catalog-service:
    image: movieservices/movie-catalog-service:latest
    container_name: movie-catalog-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
  movie-info-service:
    image: movieservices/movie-info-service:latest
    container_name: movie-info-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
  ratings-data-service:
    image: movieservices/ratings-data-service:latest
    container_name: ratings-data-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

